version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-docker-demo:latest
    container_name: node-docker-demo
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    # Runtime security hardening
    read_only: true
    tmpfs:
      - /tmp
      - /run
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    restart: unless-stopped
